name: commute_guide
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  flutter_riverpod: ^2.5.1
  firebase_messaging: ^15.0.1
  go_router: ^14.2.0
  equatable: ^2.0.5
  intl: ^0.19.0
  image_cropper: ^7.0.5
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  shared_preferences: ^2.2.3
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: any
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.1
  url_launcher: ^6.3.0
  flutter_map_cancellable_tile_provider: ^3.0.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  latlong2: ^0.9.1
  modal_bottom_sheet: ^3.0.0
  flutter_polyline_points: ^2.0.1
  flutter_mapbox_navigation: ^0.2.2
  flutter_compass: ^0.8.0
  pull_down_button: ^0.9.4
  flutter_datetime_picker_plus: ^2.2.0
  share_plus: ^9.0.0
  flutter_slidable: ^3.1.0
  firebase_dynamic_links: ^6.0.3
  local_auth: ^2.2.0
  flutter_speed_dial: ^7.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher_foreground"
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#272361"
  adaptive_icon_foreground: "assets/logos/logo.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/logos/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/maps/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
