// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfdV202ZbKgeM5OAJujNzHlmZU8ALBDI',
    appId: '1:1026946489294:web:6288502d21fdab9ea2e99f',
    messagingSenderId: '1026946489294',
    projectId: 'commute-guide-d9ad7',
    authDomain: 'commute-guide-d9ad7.firebaseapp.com',
    storageBucket: 'commute-guide-d9ad7.appspot.com',
    measurementId: 'G-FJ3L8ZHG4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10ov6uAg3O2SNyQhvJuKpBPl1CHKufPg',
    appId: '1:1026946489294:android:55e78336c9b4c208a2e99f',
    messagingSenderId: '1026946489294',
    projectId: 'commute-guide-d9ad7',
    storageBucket: 'commute-guide-d9ad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyKEuLjpdmeNH0zCtmDKpkRob_2wTW30',
    appId: '1:1026946489294:ios:91e938b67b4083d2a2e99f',
    messagingSenderId: '1026946489294',
    projectId: 'commute-guide-d9ad7',
    storageBucket: 'commute-guide-d9ad7.appspot.com',
    iosClientId:
        '1026946489294-upree2klejivirgdd6ajefeilbkgbr4l.apps.googleusercontent.com',
    iosBundleId: 'com.commuteguide.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyKEuLjpdmeNH0zCtmDKpkRob_2wTW30',
    appId: '1:1026946489294:ios:91e938b67b4083d2a2e99f',
    messagingSenderId: '1026946489294',
    projectId: 'commute-guide-d9ad7',
    storageBucket: 'commute-guide-d9ad7.appspot.com',
    iosClientId:
        '1026946489294-upree2klejivirgdd6ajefeilbkgbr4l.apps.googleusercontent.com',
    iosBundleId: 'com.commuteguide.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyfdV202ZbKgeM5OAJujNzHlmZU8ALBDI',
    appId: '1:1026946489294:web:a1f00ae77e09bfa6a2e99f',
    messagingSenderId: '1026946489294',
    projectId: 'commute-guide-d9ad7',
    authDomain: 'commute-guide-d9ad7.firebaseapp.com',
    storageBucket: 'commute-guide-d9ad7.appspot.com',
    measurementId: 'G-VNF9FBMCNP',
  );
}
